-- ============================================================
-- OTP Verifications Table
-- ============================================================
-- This table stores pending OTPs generated by the Edge Function
-- for verification since we are using the MSG91 Flow/SMS API.

CREATE TABLE IF NOT EXISTS otp_verifications (
  mobile TEXT PRIMARY KEY,
  otp TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE otp_verifications ENABLE ROW LEVEL SECURITY;

-- Allow the Edge Function (service_role) to manage these records
-- Note: Service role bypasses RLS by default, but we'll add policies for clarity
CREATE POLICY "Allow service role full access" ON otp_verifications
  FOR ALL
  USING (true)
  WITH CHECK (true);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_otp_verifications_mobile ON otp_verifications(mobile);
